version: "3.8"
services:
  polkadot:
    container_name: polkadot
    image: chevdor/polkadot:latest
    ports:
      - "9944:9944"
      - "30333:30333"
      - "9933:9933"
    command: 'polkadot --chain polkadot --unsafe-ws-external --rpc-cors=all --name ommnia-polkadot-test'