version: '3'
services:
  avamainnet:
    image: avaplatform/avalanchego
    container_name: avamainnet
    #command: ["daemon", "--migrate=true", "--enable-pubsub-experiment"]
    command:
      [
        "/avalanchego/build/avalanchego",
        "--db-dir=/data/avax",
#        "--bootstrap-retry-max-attempts=10000",
        "--api-admin-enabled=true",
        "--http-host=0.0.0.0",
        "--bootstrap-retry-enabled"
      ]
    ports:
      - 9650:9650
      - 9651:9651
    #volumes:
     # - ./avax-data:/data/avax
    restart: unless-stopped

  avatestnet:
    image: avaplatform/avalanchego
    container_name: avatestnet
    #command: ["daemon", "--migrate=true", "--enable-pubsub-experiment"]
    command:
      [
        "/avalanchego/build/avalanchego",
        "--db-dir=/data/avax",
        #"--bootstrap-retry-max-attempts=10000",
        "--api-admin-enabled=true",
        "--network-id=fuji",
        "--http-host=0.0.0.0",
        "--bootstrap-retry-enabled"
      ]
    ports:
      - 9660:9650
      - 9661:9651
    #volumes:
     # - ./avax-data:/data/avax
    restart: unless-stopped