version: '3'
services:
  avamainnet:
    image: avaplatform/avalanchego
    container_name: avamainnet
    command:
      [
        "/avalanchego/build/avalanchego",
        "./build/avalanchego",
        "--db-dir=/data/avax/main",
      ]
    ports:
      - 9660:9650
      - 9661:9651
    volumes:
      - ./avax-data:/data/avax/main
    restart: unless-stopped

  avatestnet:
    image: avaplatform/avalanchego
    container_name: avatestnet
    command:
      [
        "/avalanchego/build/avalanchego",
        "--network-id=fuji",
      ]
    ports:
      - 9670:9650
      - 9671:9651
    volumes:
      - ./avax-data:/test/avax
    restart: unless-stopped