- hosts: all
  become: true

  tasks:

    - name: Copy Bitcoin folder
      copy:
        src: ~/learn/omnia/omnia-nodes-test/bitcoin
        dest: ~/omnia
        force: yes

    - name: Run bitcoin mainnet and testnetnodes
      docker_compose:
        project_src: omnia/bitcoin 
        state: present