version: "3"
services:
  bitcoind:
    image: amacneil/bitcoin
    command: bitcoind
    healthcheck:
      test: ["CMD", "/entrypoint.sh", "bitcoin-cli", "getinfo"]
    ports:
      - "8333:8333"
    volumes:
      - bitcoin-data:/data
    networks:
      - bitcoin

  bitcointest:
    image: amacneil/bitcoin
    command: bitcoind -testnet
    healthcheck:
      test: ["CMD", "/entrypoint.sh", "bitcoin-cli", "getinfo"]
    ports:
      # change to 18333 if running testnet
      - "18333:18333"
    volumes:
      - bitcoin-data:/data
    networks:
      - bitcoin

  bitcoin-cli:
    image: amacneil/bitcoin
    entrypoint: ["/entrypoint.sh", "bitcoin-cli"]
    command: ""
    depends_on:
      - bitcoind
    network_mode: service:bitcoind

networks:
  bitcoin:

volumes:
  bitcoin-data: